name: Android CI - Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget zip gnupg2 qemu-user-static

      - name: Ensure Android SDK root
        env:
          ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
        run: |
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV

      - name: Download Android commandline tools
        env:
          ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
        run: |
          cd $ANDROID_SDK_ROOT
          # download latest commandline tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d cmdline-tools-temp
          mkdir -p cmdline-tools/latest
          mv cmdline-tools-temp/cmdline-tools/* cmdline-tools/latest/
          rm -rf cmdline-tools.zip cmdline-tools-temp
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Install Android SDK packages
        env:
          ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
        run: |
          yes | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" --install "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Accept Licenses
        env:
          ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
        run: |
          yes | sdkmanager --licenses --sdk_root="$ANDROID_SDK_ROOT" || true

      - name: Ensure Gradle wrapper
        run: |
          if [ ! -f ./gradlew ]; then
            echo 'Gradle wrapper not found - installing gradle and generating wrapper'
            sudo apt-get install -y gradle
            gradle wrapper --gradle-version 8.1.1
            chmod +x gradlew
          fi

      - name: Build debug APK
        env:
          ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
        run: |
          chmod +x ./gradlew || true
          ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
